// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVmCHXaaCOOURqato7-yTm61vJvmGUKxU',
    appId: '1:914991214745:web:df85ff2020568509af8808',
    messagingSenderId: '914991214745',
    projectId: 'diary-school-307f0',
    authDomain: 'diary-school-307f0.firebaseapp.com',
    storageBucket: 'diary-school-307f0.firebasestorage.app',
    measurementId: 'G-BLQRDP1GK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs5oXnTuSNXBfoj5aTUZ6GjrSNCg29GqI',
    appId: '1:914991214745:android:24e033441679f9dbaf8808',
    messagingSenderId: '914991214745',
    projectId: 'diary-school-307f0',
    storageBucket: 'diary-school-307f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGAKlUyQ-YeMdHpI_m1vLMS8_pbLpRTpk',
    appId: '1:914991214745:ios:7d14fd4e7a984b1baf8808',
    messagingSenderId: '914991214745',
    projectId: 'diary-school-307f0',
    storageBucket: 'diary-school-307f0.firebasestorage.app',
    iosBundleId: 'com.example.diarySchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGAKlUyQ-YeMdHpI_m1vLMS8_pbLpRTpk',
    appId: '1:914991214745:ios:7d14fd4e7a984b1baf8808',
    messagingSenderId: '914991214745',
    projectId: 'diary-school-307f0',
    storageBucket: 'diary-school-307f0.firebasestorage.app',
    iosBundleId: 'com.example.diarySchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVmCHXaaCOOURqato7-yTm61vJvmGUKxU',
    appId: '1:914991214745:web:dc4ec1256d192828af8808',
    messagingSenderId: '914991214745',
    projectId: 'diary-school-307f0',
    authDomain: 'diary-school-307f0.firebaseapp.com',
    storageBucket: 'diary-school-307f0.firebasestorage.app',
    measurementId: 'G-NRVRFBYYHK',
  );

}